# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.12.0
_src_path: gh:radio-aktywne/template-meta
accountname: radio-aktywne
description: NixOS configs template ❄️
reponame: template-nixos
repourl: https://github.com/radio-aktywne/template-nixos
templatename: nixos
type: generic
